Add bookings
anji-mito/java-shareit pull request #2
Opened 2023-08-11 21:07 UTC by anji-mito

2023-08-12 10:51 UTC, FanaticFiz requested changes
Финальный комментарий на Я.Практикуме

2023-08-12 10:51 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/booking/mapper/BookingConverter.java
> +        this.modelMapper = new ModelMapper();
Создаем его три раза, для каждой сущности.
Нельзя ли иметь один на все приложение?

2023-08-12 10:51 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +    @Column(name = "start_date")
Какие-то неадекватные отступы - запутало еще больше, какая аннотация к какому полю относится?

2023-08-12 10:51 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        if (booking.isPresent()) {
Вот давай так больше не писать... Всегда плохо более 3-х вложенностей.

Всй что нужно это инвертировать эти условия, вот так:

```
    public BookingDto approveBooking(boolean isApproved, long bookingId, long userId) {
        userService.getById(userId);
        
        var booking = bookingRepository.findById(bookingId);
        if (booking.isEmpty()) {
            throw new NotFoundException("Booking with id " + bookingId + " does not exist");
        }

        if (booking.get().getItem().getOwner().getId() != userId) {
            throw new NotFoundException("Booking with id " + bookingId + " does not belong to this user");
        }
 
        if (isApproved) {
.........
```

2023-08-12 10:51 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        if (booking.isPresent()) {
А теперь!
Воспользуемся `Optional` правильно!
У него есть методы, посмотри самостоятельно какие, а тут я покажу самый часто применимый из них: `orElseThrow`

```
        Booking booking = bookingRepository
                .findById(bookingId)
                .orElseThrow(() -> new NotFoundException("Booking with id " + bookingId + " does not exist"));
```

В итоге нам и в дальнейшем не придется писать `booking.get()` - мы уже раскрыли Optional и взяли от туда значение, которое точно есть. Если бы его небыло - был бы выкинут ексепшн.

2023-08-12 10:51 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        if (booking.isPresent()) {
Переработай код в этом ключе и в других местах.

2023-08-12 10:51 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/item/mapper/BookerForItemConverter.java
> +    public BookingForItemDto convertToDto(Optional<Booking> booking) {
Не бывает `Optional` для входного параметра метода.
Ну т.е., как мы видим, такой возможно написать! ))
Но так не делают. 
Ну и у тебя это вылезло просто из-за того что ты не раскрывал его до этого.

Так что тут просто: `convertToDto(Booking booking)`

2023-08-12 10:51 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/item/repository/ItemRepository.java
> +    List<Item> findByNameAndDescriptionContainingIgnoreCase(String searchQuery);
Когда ты пишешь свой `query` ты свободен в названии метода.
Может получится сделать его более "человечным"?

2023-08-12 10:51 UTC, FanaticFiz commented on src/main/resources/application.yml
> +      ddl-auto: none
Отлично! Все свойства на своих местах.
Обычно копипастят из инета - и попадаются старые не актуальные конфиги.

2023-08-12 10:51 UTC, FanaticFiz commented on src/main/resources/schema.sql
> +    text       VARCHAR(512)                            NOT NULL,
`text VARCHAR(512)` - мало дал... Есть прям тип в postgresql - `text`

2023-08-13 08:26 UTC, FanaticFiz requested changes
Финальный комментарий на Я.Практикуме

2023-08-13 17:30 UTC, anji-mito commented
Забыл запушить изменения :)

2023-08-13 18:35 UTC, FanaticFiz approved these changes

2023-08-13 18:39 UTC, merged