Add item requests
anji-mito/java-shareit pull request #3
Opened 2023-08-19 10:15 UTC by anji-mito

2023-08-20 19:42 UTC, FanaticFiz requested changes
Финальный комментарий на Я.Практикуме

2023-08-20 19:42 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/booking/repository/BookingRepository.java
> +    List<Booking> findAllByBookerIdAndEndIsBeforeOrderByStartDesc(long userId, LocalDateTime end, PageRequest pageRequest);
Работать нужно с интерфейсами. 
`PageRequest` - это конкретный класс, а тебе нужен интерфейс `Pageable`

2023-08-20 19:42 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/request/service/RequestServiceImpl.java
> +        itemRequestDto.setCreated(LocalDateTime.now());
`LocalDateTime.now()` - кстати, как ты думаешь какое время ты получишь тут, вызвав этот метод?

Комментируй прям тут.

2023-08-20 19:42 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/request/service/RequestServiceImpl.java
> +        return itemRequestConverter.convertToDto(requestRepository.findById(id)
Лучше не так выстроить код. Все таки главное тут это `findById` а конвертер вспомогательный.

```
    @Override
    public ItemRequestDto getById(long requestId, long userId) {
        getUserById(userId);

        return requestRepository
                .findById(requestId)
                .map(itemRequestConverter::convertToDto)
                .orElseThrow(() -> new NotFoundException("Request with id: " + requestId + " does not exist"));
    }
```

Не забывай что у Optional есть метод `map`

2023-08-20 19:58 UTC, anji-mito commented on src/main/java/ru/practicum/shareit/request/service/RequestServiceImpl.java
> +        itemRequestDto.setCreated(LocalDateTime.now());
Локальное время на сервере, думаю, можно как то реализовать в дальнейшем так, чтобы возвращал время по таймзону клиента, или как лучше будет сделать? Хотелось бы узнать как подобное решают на коммерческих продуктах, когда много логики завязаное на времени, например, те же букинги, возвращаемые списки сильно зависят от времени

2023-08-20 20:06 UTC, anji-mito commented on src/main/java/ru/practicum/shareit/request/service/RequestServiceImpl.java
> +        itemRequestDto.setCreated(LocalDateTime.now());
Локальное время на сервере, понимаю, что много проблем могут возникнуть с тайзонами клиентов, как можно будет сделать лучше? записывать в базу время полученного запроса?

2023-08-21 05:55 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/request/service/RequestServiceImpl.java
> +        itemRequestDto.setCreated(LocalDateTime.now());
Верно. 
В `.now()` используем не задумываясь метод без параметра. 
А временную зону можно указывать явно, чтобы она не зависела от настроек окружения.
Можно изменить кодом для всего приложения и продолжать использовать `now()`
Можно задавать при старте параметром `-Duser.timezone`

2023-08-21 06:01 UTC, FanaticFiz approved these changes

2023-08-21 17:32 UTC, FanaticFiz approved these changes

2023-08-22 08:15 UTC, merged